Enabled MacOS build

diff --git a/.github/workflows/build-targets.yml b/.github/workflows/build-targets.yml
--- a/.github/workflows/build-targets.yml
+++ b/.github/workflows/build-targets.yml
@@ -535,21 +535,52 @@ jobs:
     #              x86_64
     #              x86
     #              armeabi-v7a
-    #          - target-os: OSX
-    #            runs-on: macos-latest
-    #            shell: bash
-    #            setup-script: |
-    #              echo "Setup for OSX Build"
-    #              find /Applications/Xcode* -maxdepth 0 -ls
-    #              sudo xcode-select --switch "$(find /Applications/Xcode*.app -maxdepth 0 | sort -V | tail -1)/Contents/Developer"
-    #              sudo rm -Rf /Library/Developer/CommandLineTools/SDKs/*
-    #            cmake-script: |
-    #              cd build/$TARGET_OS
-    #              mkdir Release
-    #              cd Release
-    #              cmake -S .. -DCMAKE_BUILD_TYPE=$BUILD_TYPE
-    #              echo "Compiling $TARGET_OS version $LIBRARY_VERSION of $LIBRARY_NAME"
-    #              make $LIBRARY_NAME
+          - target-os: OSX
+            runs-on: macos-latest
+            shell: bash
+            setup-script: |
+              echo "Setup for OSX Build"
+              find /Applications/Xcode* -maxdepth 0 -ls
+              sudo xcode-select --switch "$(find /Applications/Xcode*.app -maxdepth 0 | sort -V | tail -1)/Contents/Developer"
+              sudo rm -Rf /Library/Developer/CommandLineTools/SDKs/*
+            cmake-init-script: |
+              cd build/$TARGET_OS
+              mkdir $BUILD_TYPE
+              cd $BUILD_TYPE
+              cmake -S .. -DCMAKE_BUILD_TYPE=$BUILD_TYPE
+            cmake-compile-script: |
+              echo "Compiling $TARGET_OS version $TARGET_SHA of $TARGET_NAME $BUILD_TYPE mode"
+              make $TARGET_NAME -j$(nproc)
+              make install
+            release-target: |
+              # Check if release already defined e.g. MacOS-master-release
+              GITHUB_RELEASE_NAME=${TARGET_OS}-${BRANCH}-${BUILD_TYPE}
+              gh release view ${GITHUB_RELEASE_NAME}
+              if [ $? -ne 0 ]
+              then
+                echo "Creating github release with tag: ${GITHUB_RELEASE_NAME}"
+                
+                RELEASE_TYPE="--latest"
+                if [[ "${BUILD_TYPE}" != "Release" ]]; 
+                then
+                  RELEASE_TYPE="--prerelease"
+                fi
+                
+                # Create release on github
+                gh release create ${GITHUB_RELEASE_NAME} -n "${BRANCH} branch" --target ${BRANCH} ${RELEASE_TYPE} -t "${TARGET_OS} ${BRANCH} branch ${BUILD_TYPE} build"
+                if [ $? -ne 0 ]
+                then
+                  set -e
+                  echo "Failed to create github release with tag: ${GITHUB_RELEASE_NAME}"
+                  exit 1
+                fi
+              fi
+              
+              COMPRESSED_TARGET="${TARGET_NAME}-lib.tar.gz"
+              echo "Compressing ${TARGET_OS} version ${TARGET_SHA} of ${TARGET_NAME} ${BUILD_TYPE} mode (target build folder: ${TARGET_DIRECTORY})"
+              tar -zcf ${COMPRESSED_TARGET} ${TARGET_DIRECTORY} 
+              echo "Uploading target ${COMPRESSED_TARGET} to github release ${GITHUB_RELEASE_NAME}"
+              gh release upload --clobber ${GITHUB_RELEASE_NAME} ${COMPRESSED_TARGET}
     #          - target-os: iOS
     #            runs-on: macos-latest
     #            shell: bash
