SAving source folders to github release

diff --git a/.github/workflows/build-targets.yml b/.github/workflows/build-targets.yml
--- a/.github/workflows/build-targets.yml
+++ b/.github/workflows/build-targets.yml
@@ -301,6 +301,71 @@ jobs:
         shell: bash
         working-directory: ${{github.workspace}}
 
+  save-target-sources:
+    needs: [ setup-src-cache, cache-src, create-targets-matrix ]
+    # if: |
+    #   always() &&
+    #   needs.setup-src-cache.result == 'success' &&
+    #   needs.create-targets-matrix.result == 'success' &&
+    #   (needs.cache-src.result == 'success' || needs.cache-src.result == 'skipped')
+    strategy:
+      fail-fast: false
+      
+      matrix:
+        target-os: [Linux, Windows, OSX, iOS, Android]
+        build-type: [ Release, Debug ]
+    runs-on: ubuntu-latest
+    steps:
+      - name: Create library Keys and Paths to release sources
+        id: create-src-cache-keys
+        run: |
+          # build array of library names
+          IFS=$'\n' read -d '|' -ra TARGET_NAMES <<< "$(echo -ne '${{ needs.create-targets-matrix.outputs.TARGET_NAMES }}|')"
+          IFS=$'\n' read -d '|' -ra TARGET_SHAS <<< "$(echo -ne '${{ needs.create-targets-matrix.outputs.TARGET_SHAS }}|')"
+
+          TARGET_OS="${{ matrix.target-os }}"
+          BUILD_TYPE="${{ matrix.build-type }}"
+          BRANCH=${{ github.ref_name }}
+          GITHUB_RELEASE_NAME=${TARGET_OS}-${BRANCH}-${BUILD_TYPE}
+
+      - name: Creating github release tag
+        id: create-github-release-tag
+        run: |
+          gh release view ${GITHUB_RELEASE_NAME}
+          if [ $? -eq 1 ]
+          then
+            echo "Creating github release with tag: ${GITHUB_RELEASE_NAME}"
+          
+            RELEASE_TYPE="--latest"
+            if [[ "${BUILD_TYPE}" != "Release" ]]; 
+            then
+              RELEASE_TYPE="--prerelease"
+            fi
+          
+            # Create release on github
+            gh release create ${GITHUB_RELEASE_NAME} -n "${BRANCH} branch" --target ${BRANCH} ${RELEASE_TYPE} -t "${TARGET_OS} ${BRANCH} branch ${BUILD_TYPE} build"
+            if [ $? -eq 1 ]
+            then
+              set -e
+              echo "Failed to create github release with tag: ${GITHUB_RELEASE_NAME}"
+              return 1
+            fi
+          fi
+
+      - name: Compress and upload targets source folder
+        id: compress-targets-source
+        run: |
+          for i in "${!TARGET_NAMES[@]}"; do
+            TARGET_NAME="${TARGET_NAMES[i]}"
+            TARGET_SHA="${TARGET_SHAS[i]}"
+            COMPRESSED_TARGET_SRC="${TARGET_NAME}-src.tar.gz"
+            echo "Compressing ${TARGET_OS} version ${TARGET_SHA} of ${TARGET_NAME} source folder"
+            tar -zcvf ${COMPRESSED_TARGET_SRC} ${TARGET_NAME} 
+            echo "Uploading target ${COMPRESSED_TARGET_SRC} to github release ${GITHUB_RELEASE_NAME}"
+            gh release upload --clobber ${GITHUB_RELEASE_NAME} ${COMPRESSED_TARGET_SRC}
+          done
+
+
   build-targets-matrix:
     needs: [ setup-src-cache, cache-src, create-targets-matrix ]
     if: |
