Check if gh release view command failed

diff --git a/.github/workflows/build-targets.yml b/.github/workflows/build-targets.yml
--- a/.github/workflows/build-targets.yml
+++ b/.github/workflows/build-targets.yml
@@ -480,12 +480,19 @@ jobs:
           IFS=$'\n' read -d '|' -ra TARGET_NAMES <<< "$(echo -ne '${{ needs.create-targets-matrix.outputs.TARGET_NAMES }}|')"
           IFS=$'\n' read -d '|' -ra TARGET_SHAS <<< "$(echo -ne '${{ needs.create-targets-matrix.outputs.TARGET_SHAS }}|')"
           
+          set +e
+          
           GITHUB_RELEASE_NAME=${TARGET_OS}-${BRANCH}-${BUILD_TYPE}
           for i in "${!TARGET_NAMES[@]}"; do
             TARGET_NAME="${TARGET_NAMES[i]}"
             TARGET_SHA="${TARGET_SHAS[i]}"
             COMPRESSED_TARGET="${TARGET_NAME}-${TARGET_SHA}.tar.gz"
             targetBuilt=`gh release view ${GITHUB_RELEASE_NAME} --json assets --jq 'any(.assets[]; .name == "${COMPRESSED_TARGET}")'`
+            if [ $? -eq 1 ]
+            then
+              echo "gh release view command failed for ${GITHUB_RELEASE_NAME}"
+              targetBuilt=false
+            fi
             echo "Check if ${COMPRESSED_TARGET} found on ${GITHUB_RELEASE_NAME}: ${targetBuilt}"
             targetBuiltList+="${targetBuilt}"
           done
