Update release.json file after each successful target built

diff --git a/.github/workflows/build-targets.yml b/.github/workflows/build-targets.yml
--- a/.github/workflows/build-targets.yml
+++ b/.github/workflows/build-targets.yml
@@ -589,6 +589,35 @@ jobs:
           - target-os: $TARGET_OS
             runs-on: $TARGET_RUNS_ON
             shell: bash
+            upload-release-json: |
+              GITHUB_RELEASE_NAME=${TARGET_OS}-${BRANCH}-${BUILD_TYPE}
+              
+              retValue=1
+              numberOfTries=1
+              until [[ $retValue -eq 0 ]]
+              do
+                if [[ $numberOfTries -gt 5 ]]; then
+                  break
+                fi
+                
+                echo "#${numberOfTries} Uploading release.json to github release ${GITHUB_RELEASE_NAME}"
+                gh release upload --clobber ${GITHUB_RELEASE_NAME} release.json
+                retValue=$?
+                
+                if [[ $retValue -ne 0 ]]; then
+                  echo "gh release upload failed, sleep 2 sec before next try"
+                  sleep 2
+                fi
+
+                ((numberOfTries++))
+              done
+
+              if [[ $retValue -ne 0 ]]; then
+                set -e
+                echo "Failed to upload release.json to github release ${GITHUB_RELEASE_NAME}"
+                exit 1
+              fi
+
             release-target: |
               # Check if release already defined e.g. Linux-master-release
               GITHUB_RELEASE_NAME=${TARGET_OS}-${BRANCH}-${BUILD_TYPE}
@@ -891,6 +920,9 @@ jobs:
 
             # Upload JSON file release 
             jq <<< $releaseJsonStr > release.json
+
+            ${{ matrix.target-save-data.upload-release-json }}
+
           done
 
       - name: Upload JSON file release on build failure
@@ -982,28 +1014,5 @@ jobs:
           # Upload JSON file release 
           jq <<< $jsonStr > release.json
 
-          retValue=1
-          numberOfTries=1
-          until [[ $retValue -eq 0 ]]
-          do
-            if [[ $numberOfTries -gt 5 ]]; then
-              break
-            fi
-            
-            echo "#${numberOfTries} Uploading release.json to github release ${GITHUB_RELEASE_NAME}"
-            gh release upload --clobber ${GITHUB_RELEASE_NAME} release.json
-            retValue=$?
-            
-            if [[ $retValue -ne 0 ]]; then
-              echo "gh release upload failed, sleep 2 sec before next try"
-              sleep 2
-            fi
-
-            ((numberOfTries++))
-          done
-
-          if [[ $retValue -ne 0 ]]; then
-            set -e
-            echo "Failed to upload release.json to github release ${GITHUB_RELEASE_NAME}"
-            exit 1
-          fi
+          ${{ matrix.target-save-data.upload-release-json }}
+          
