Restore cache before upload sources

diff --git a/.github/workflows/build-targets.yml b/.github/workflows/build-targets.yml
--- a/.github/workflows/build-targets.yml
+++ b/.github/workflows/build-targets.yml
@@ -307,7 +307,8 @@ jobs:
       always() &&
       needs.setup-src-cache.result == 'success' &&
       needs.create-targets-matrix.result == 'success' &&
-      (needs.cache-src.result == 'success' || needs.cache-src.result == 'skipped')    
+      (needs.cache-src.result == 'success' || needs.cache-src.result == 'skipped') &&
+      needs.create-targets-matrix.result == 'success'    
     strategy:
       fail-fast: false
       matrix:
@@ -359,7 +360,27 @@ jobs:
           fi
 
           set -e
-
+      - name: Cache Third Party Directory
+        uses: GeniusVentures/cache-multi/restore@v3.2.3
+        id: cache-tp-source-directory
+        with:
+          key: ${{ needs.setup-src-cache.outputs.THIRD_PARTY_CACHE_NAME_KEY }}
+          path: |
+            !.git/**
+            ./**
+  
+      - if: (steps.cache-tp-source-directory.outputs.cache-hit != 'true')
+        run: |
+          echo "Couldn't find cached thirdparty code, ${{ needs.setup-src-cache.outputs.THIRD_PARTY_CACHE_NAME_KEY }} fatal error!"
+          exit 1
+  
+      - name: Cache Submodule Source Files without .git
+        id: cache-source-directory
+        uses: GeniusVentures/cache-multi/restoremulti@v3.2.3
+        with:
+          multi-keys: ${{ needs.setup-src-cache.outputs.CACHE_MULTI_PARAMETER_NAME_KEYS }}
+          paths: ${{ needs.setup-src-cache.outputs.CACHE_MULTI_PARAMETER_PATHS }}
+  
       - name: Compress and upload targets source folder
         id: compress-targets-source
         working-directory: ${{github.workspace}}
