Enabled windows, OSX and iOS builds also

diff --git a/.github/workflows/build-targets.yml b/.github/workflows/build-targets.yml
--- a/.github/workflows/build-targets.yml
+++ b/.github/workflows/build-targets.yml
@@ -473,40 +473,6 @@ jobs:
       fail-fast: false
       matrix:
         build-type: [ Release, Debug ]
-        target-save-data: 
-          - target-os: $TARGET_OS
-            runs-on: $TARGET_RUNS_ON
-            shell: bash
-            release-target: |
-              # Check if release already defined e.g. Linux-master-release
-              GITHUB_RELEASE_NAME=${TARGET_OS}-${BRANCH}-${BUILD_TYPE}
-              gh release view ${GITHUB_RELEASE_NAME}
-              if [ $? -ne 0 ]
-              then
-                echo "Creating github release with tag: ${GITHUB_RELEASE_NAME}"
-                
-                RELEASE_TYPE="--latest"
-                if [[ "${BUILD_TYPE}" != "Release" ]]; 
-                then
-                  RELEASE_TYPE="--prerelease"
-                fi
-                
-                # Create release on github
-                gh release create ${GITHUB_RELEASE_NAME} -n "${BRANCH} branch" --target ${BRANCH} ${RELEASE_TYPE} -t "${TARGET_OS} ${BRANCH} branch ${BUILD_TYPE} build"
-                if [ $? -ne 0 ]
-                then
-                  set -e
-                  echo "Failed to create github release with tag: ${GITHUB_RELEASE_NAME}"
-                  exit 1
-                fi
-              fi
-              
-              COMPRESSED_TARGET="${TARGET_NAME}-lib.tar.gz"
-              echo "Compressing ${TARGET_OS} version ${TARGET_SHA} of ${TARGET_NAME} ${BUILD_TYPE} mode (target build folder: ${TARGET_DIRECTORY})"
-              tar -zcf ${COMPRESSED_TARGET} ${TARGET_DIRECTORY} 
-              echo "Uploading target ${COMPRESSED_TARGET} to github release ${GITHUB_RELEASE_NAME}"
-              gh release upload --clobber ${GITHUB_RELEASE_NAME} ${COMPRESSED_TARGET}
-
         target-build-data:
           # --------------------------------------------------------------------------
           - target-os: Linux
@@ -552,89 +518,101 @@ jobs:
               make $TARGET_NAME -j$(nproc)
               make install  
 
-
           # --------------------------------------------------------------------------    
-          # - target-os: OSX
-          #   runs-on: macos-latest
-          #   shell: bash
-          #   setup-script: |
-          #     echo "Setup for OSX Build"
-          #     find /Applications/Xcode* -maxdepth 0 -ls
-          #     sudo xcode-select --switch "$(find /Applications -mindepth 1 -maxdepth 1 ! -type l | grep "Xcode_[\.0-9]*app" | sort -V | tail -1)/Contents/Developer"
-          #     sudo rm -Rf /Library/Developer/CommandLineTools/SDKs/*        
-          #   cmake-init-script: |
-          #     cd build/$TARGET_OS
-          #     mkdir $BUILD_TYPE
-          #     cd $BUILD_TYPE
-          #     cmake -S .. -DCMAKE_BUILD_TYPE=$BUILD_TYPE
-          #   cmake-compile-script: |
-          #     echo "Compiling $TARGET_OS version $TARGET_SHA of $TARGET_NAME $BUILD_TYPE mode"
-          #     make $TARGET_NAME -j$(nproc)
-          #     make install
-          #   release-target: |
-          #     # Check if release already defined e.g. MacOS-master-release
-          #     GITHUB_RELEASE_NAME=${TARGET_OS}-${BRANCH}-${BUILD_TYPE}
-          #     gh release view ${GITHUB_RELEASE_NAME}
-          #     if [ $? -ne 0 ]
-          #     then
-          #       echo "Creating github release with tag: ${GITHUB_RELEASE_NAME}"
-                
-          #       RELEASE_TYPE="--latest"
-          #       if [[ "${BUILD_TYPE}" != "Release" ]]; 
-          #       then
-          #         RELEASE_TYPE="--prerelease"
-          #       fi
-                
-          #       # Create release on github
-          #       gh release create ${GITHUB_RELEASE_NAME} -n "${BRANCH} branch" --target ${BRANCH} ${RELEASE_TYPE} -t "${TARGET_OS} ${BRANCH} branch ${BUILD_TYPE} build"
-          #       if [ $? -ne 0 ]
-          #       then
-          #         set -e
-          #         echo "Failed to create github release with tag: ${GITHUB_RELEASE_NAME}"
-          #         exit 1
-          #       fi
-          #     fi
-              
-          #     COMPRESSED_TARGET="${TARGET_NAME}-lib.tar.gz"
-          #     echo "Compressing ${TARGET_OS} version ${TARGET_SHA} of ${TARGET_NAME} ${BUILD_TYPE} mode (target build folder: ${TARGET_DIRECTORY})"
-          #     tar -zcf ${COMPRESSED_TARGET} ${TARGET_DIRECTORY} 
-          #     echo "Uploading target ${COMPRESSED_TARGET} to github release ${GITHUB_RELEASE_NAME}"
-          #     gh release upload --clobber ${GITHUB_RELEASE_NAME} ${COMPRESSED_TARGET}
+          - target-os: OSX
+            runs-on: macos-latest
+            shell: bash
+            setup-script: |
+              echo "Setup for OSX Build"
+              find /Applications/Xcode* -maxdepth 0 -ls
+              sudo xcode-select --switch "$(find /Applications -mindepth 1 -maxdepth 1 ! -type l | grep "Xcode_[\.0-9]*app" | sort -V | tail -1)/Contents/Developer"
+              sudo rm -Rf /Library/Developer/CommandLineTools/SDKs/*        
+            cmake-init-script: |
+              cd build/$TARGET_OS
+              mkdir $BUILD_TYPE
+              cd $BUILD_TYPE
+              cmake -S .. -DCMAKE_BUILD_TYPE=$BUILD_TYPE
+            cmake-compile-script: |
+              echo "Compiling $TARGET_OS version $TARGET_SHA of $TARGET_NAME $BUILD_TYPE mode"
+              make $TARGET_NAME -j$(nproc)
+              make install
 
           # --------------------------------------------------------------------------
-    #          - target-os: iOS
-    #            runs-on: macos-latest
-    #            shell: bash
-    #            setup-script: |
-    #              echo "Setup for iOS Build"
-    #              find /Applications/Xcode* -maxdepth 0 -ls
-    #              sudo xcode-select --switch "$(find /Applications/Xcode*.app -maxdepth 0 | sort -V | tail -1)/Contents/Developer"
-    #              sudo rm -Rf /Library/Developer/CommandLineTools/SDKs/*
-    #            install-uses:
-    #              uses: actions/setup-python@v2
-    #              with:
-    #                python-version: '3.5'
-    #            cmake-script: |
-    #              cd build/$TARGET_OS
-    #              mkdir Release
-    #              cd Release
-    #              cmake -S .. -DCMAKE_BUILD_TYPE=$BUILD_TYPE -DiOS_ABI=arm64-v8a -DIOS_ARCH="arm64" -DENABLE_ARC=0 -DENABLE_BITCODE=0 -DENABLE_VISIBILITY=1  -DCMAKE_OSX_ARCHITECTURES=arm64 -DCMAKE_SYSTEM_PROCESSOR=arm64 -DCMAKE_TOOLCHAIN_FILE=$WORKSPACE/build/iOS/iOS.cmake
-    #              echo "Compiling $TARGET_OS version $LIBRARY_VERSION of $LIBRARY_NAME"
-    #              make $LIBRARY_NAME
+          - target-os: iOS
+            runs-on: macos-latest
+            shell: bash
+            setup-script:
+            uses: actions/setup-python@v2
+              with:
+                python-version: '3.5' 
+              |
+              echo "Setup for iOS Build"
+              find /Applications/Xcode* -maxdepth 0 -ls
+              sudo xcode-select --switch "$(find /Applications/Xcode*.app -maxdepth 0 | sort -V | tail -1)/Contents/Developer"
+              sudo rm -Rf /Library/Developer/CommandLineTools/SDKs/*              
+            cmake-init-script: |
+              cd build/$TARGET_OS
+              mkdir $BUILD_TYPE
+              cd $BUILD_TYPE
+              cmake -S .. -DCMAKE_BUILD_TYPE=$BUILD_TYPE -DiOS_ABI=arm64-v8a -DIOS_ARCH="arm64" -DENABLE_ARC=0 -DENABLE_BITCODE=0 -DENABLE_VISIBILITY=1  -DCMAKE_OSX_ARCHITECTURES=arm64 -DCMAKE_SYSTEM_PROCESSOR=arm64 -DCMAKE_TOOLCHAIN_FILE=$WORKSPACE/build/iOS/iOS.cmake
+            cmake-compile-script: |  
+              echo "Compiling $TARGET_OS version $TARGET_SHA of $TARGET_NAME $BUILD_TYPE mode"
+              make $TARGET_NAME -j$(nproc)
+              make install
     
-              # --------------------------------------------------------------------------
-    #          - target-os: Windows
-    #            runs-on: windows-2022
-    #            setup-script: |
-    #              echo "Setup for Windows Build"
-    #            install-uses:
-    #              name: Configure build for Windows 10 x64
-    #              uses: ilammy/msvc-dev-cmd@v1
-    #              with:
-    #                arch: amd64
-    #                sdk: 10.0.22621.0
-    #                vsversion: 17
+          # --------------------------------------------------------------------------
+          - target-os: Windows
+            runs-on: windows-2022
+            setup-script: 
+              uses: ilammy/msvc-dev-cmd@v1
+              with:
+                arch: amd64
+                sdk: 10.0.22621.0
+                vsversion: 17
+              echo "Setup for Windows Build"
+            cmake-init-script: |
+              cd build/$TARGET_OS
+              mkdir $BUILD_TYPE
+              cd $BUILD_TYPE
+              cmake -S .. -DCMAKE_BUILD_TYPE=$BUILD_TYPE -G "Visual Studio 17 2022" -A x64 -DCMAKE_SYSTEM_VERSION="10.0"
+            cmake-compile-script: |
+              echo "Compiling $TARGET_OS version $TARGET_SHA of $TARGET_NAME $BUILD_TYPE mode"
+              cmake --build . --target $TARGET_NAME --config $BUILD_TYPE -j$(nproc)
+              cmake --install $TARGET_NAME
 
+        target-save-data: 
+          - target-os: $TARGET_OS
+            runs-on: $TARGET_RUNS_ON
+            shell: bash
+            release-target: |
+              # Check if release already defined e.g. Linux-master-release
+              GITHUB_RELEASE_NAME=${TARGET_OS}-${BRANCH}-${BUILD_TYPE}
+              gh release view ${GITHUB_RELEASE_NAME}
+              if [ $? -ne 0 ]
+              then
+                echo "Creating github release with tag: ${GITHUB_RELEASE_NAME}"
+                
+                RELEASE_TYPE="--latest"
+                if [[ "${BUILD_TYPE}" != "Release" ]]; 
+                then
+                  RELEASE_TYPE="--prerelease"
+                fi
+                
+                # Create release on github
+                gh release create ${GITHUB_RELEASE_NAME} -n "${BRANCH} branch" --target ${BRANCH} ${RELEASE_TYPE} -t "${TARGET_OS} ${BRANCH} branch ${BUILD_TYPE} build"
+                if [ $? -ne 0 ]
+                then
+                  set -e
+                  echo "Failed to create github release with tag: ${GITHUB_RELEASE_NAME}"
+                  exit 1
+                fi
+              fi
+              
+              COMPRESSED_TARGET="${TARGET_NAME}-lib.tar.gz"
+              echo "Compressing ${TARGET_OS} version ${TARGET_SHA} of ${TARGET_NAME} ${BUILD_TYPE} mode (target build folder: ${TARGET_DIRECTORY})"
+              tar -zcf ${COMPRESSED_TARGET} ${TARGET_DIRECTORY} 
+              echo "Uploading target ${COMPRESSED_TARGET} to github release ${GITHUB_RELEASE_NAME}"
+              gh release upload --clobber ${GITHUB_RELEASE_NAME} ${COMPRESSED_TARGET}
 
     runs-on: ${{ matrix.target-build-data.runs-on }}
     outputs:
