Adding extra verbosity for github release creation

diff --git a/.github/workflows/build-targets.yml b/.github/workflows/build-targets.yml
--- a/.github/workflows/build-targets.yml
+++ b/.github/workflows/build-targets.yml
@@ -494,10 +494,12 @@ jobs:
         run: |
           TARGET_OS="${{ matrix.target-build-data.target-os }}"
           BUILD_TYPE="${{ matrix.build-type }}"
+          echo "BRANCH=${{ github.ref_name }}" >> $GITHUB_ENV
+          echo "GH_TOKEN=${{ secrets.GITHUB_TOKEN }}" >> $GITHUB_ENV
           IFS=$'\n' read -d '|' -ra TARGET_NAMES <<< "$(echo -ne '${{ needs.create-targets-matrix.outputs.TARGET_NAMES }}|')"
           IFS=$'\n' read -d '|' -ra TARGET_SHAS <<< "$(echo -ne '${{ needs.create-targets-matrix.outputs.TARGET_SHAS }}|')"
           IFS=$'\n' read -d '|' -ra CACHE_HITS <<< "$(echo -ne '${{ steps.cache-library-directory.outputs.cache-hits }}|')"
-          
+                    
           ## Setting this to not fail the workflow while checking release tag 
           set +e
           
@@ -505,8 +507,15 @@ jobs:
           gh release view $TARGET_OS-$BRANCH-$BUILD_TYPE
           if [ $? -eq 1 ]
           then
+            echo "Creating github release with tag: $TARGET_OS-$BRANCH-$BUILD_TYPE"
             # Create release on github
             gh release create $TARGET_OS-$BRANCH-$BUILD_TYPE -n "$BRANCH branch" --target $BRANCH -t "$TARGET_OS $BRANCH branch $BUILD_TYPE build"
+            if [ $? -eq 1 ]
+            then
+              set -e
+              echo "Failed to create github release with tag: $TARGET_OS-$BRANCH-$BUILD_TYPE"
+              return 1
+            fi
           fi
           
           cd "build/${TARGET_OS}/${BUILD_TYPE}"
