Getting libraries to cache and build

diff --git a/.github/workflows/test-cache.yml b/.github/workflows/test-cache.yml
--- a/.github/workflows/test-cache.yml
+++ b/.github/workflows/test-cache.yml
@@ -214,7 +214,7 @@ jobs:
       TARGET_NAMES: ${{ steps.create-target-info.outputs.TARGET_NAMES }}
       TARGET_SHAS: ${{ steps.create-target-info.outputs.TARGET_SHAS }}
       TARGET_DIRECTORIES: ${{ steps.create-target-info.outputs.TARGET_DIRECTORIES }}
-      TARGET_REPO_NAME: ${{ steps.create-target-info.outputs.TARGET_REPO_NAME }}
+      TARGET_REPO_NAMES: ${{ steps.create-target-info.outputs.TARGET_REPO_NAMES }}
     steps:
       - name: Cache Third Party Directory
         uses: GeniusVentures/cache-multi/restore@v3.2.3
@@ -290,7 +290,7 @@ jobs:
           echo "TARGET_NAMES=$cMakeNames" >> $GITHUB_OUTPUT
           echo "TARGET_SHAS=$shortSHAs" >> $GITHUB_OUTPUT
           echo "TARGET_DIRECTORIES=$buildDirectoryNames" >> $GITHUB_OUTPUT
-          echo "TARGET_REPO_NAME=$repoNames" >> $GITHUB_OUTPUT
+          echo "TARGET_REPO_NAMES=$repoNames" >> $GITHUB_OUTPUT
 
         shell: bash
         working-directory: ${{github.workspace}}
@@ -312,6 +312,14 @@ jobs:
             shell: bash
             setup-script: |
               echo "Setup for Linux Build"
+            cmake-init-script: |
+              cd build/$TARGET_OS
+              mkdir $BUILD_TYPE
+              cd $BUILD_TYPE
+              cmake .. -DCMAKE_BUILD_TYPE=$BUILD_TYPE
+            cmake-compile-script: |
+              echo "Compiling $TARGET_OS version $TARGET_SHA of $TARGET_NAME"
+              make $TARGET_NAME
 #          - target-os: Android
 #            runs-on: ubuntu-latest
 #            shell: bash
@@ -377,13 +385,36 @@ jobs:
 
     runs-on: ${{ matrix.target-build-data.runs-on }}
     steps:
-      - name: dumping matrix for each run
+
+      - name: Create library Keys and Paths to Cache/build
+        id: create-lib-cache-keys
         run: |
-          echo -e "matrix: ${{ toJson(matrix) }}"
-          echo -e "cmakeNames: ${{ needs.create-targets-matrix.outputs.TARGET_NAMES }}"
-          echo -e "targetSHAs: ${{ needs.create-targets-matrix.outputs.TARGET_SHAS }}"
-          echo -e "buildDirs: ${{ needs.create-targets-matrix.outputs.TARGET_DIRECTORIES }}"
-          echo -e "targetRepoName: ${{ needs.create-targets-matrix.outputs.TARGET_REPO_NAME }}"          
+          # build array of library names
+          IFS=$'\n' read -d '' -ra TARGET_REPO_NAMES <<< "${{ needs.create-targets-matrix.outputs.TARGET_REPO_NAMES }}"
+          IFS=$'\n' read -d '' -ra TARGET_SHAS <<< "${{ needs.create-targets-matrix.outputs.TARGET_SHAS }}"
+          IFS=$'\n' read -d '' -ra TARGET_DIRECTORIES <<< "${{ needs.create-targets-matrix.outputs.TARGET_DIRECTORIES }}"
+          LIB_CACHE_NAME_KEYS="[ "
+          LIB_CACHE_PATHS="[ "
+          first=true
+          for i in "${!TARGET_REPO_NAMES[@]}"; do
+            if [[ "$first" != "true" ]]; then
+              LIB_CACHE_NAME_KEYS+=", "
+              LIB_CACHE_PATHS+=", "
+            fi
+            first=false
+            LIB_CACHE_NAME_KEYS+="\"l/${{ matrix.target-os }}/${{ matrix.build-type }}/${TARGET_REPO_NAMES[i]}-${TARGET_SHAS[i]}\""
+            LIB_CACHE_PATHS+="[\"./build/${{ matrix.target-os }}/${{ matrix.build-type }}/${TARGET_DIRECTORIES[i]}/**\"]"
+          done
+
+          LIB_CACHE_NAME_KEYS+=" ]"
+          echo "LIB_CACHE_NAME_KEYS=$LIB_CACHE_NAME_KEYS" >> $GITHUB_OUTPUT
+
+          LIB_CACHE_PATHS+=" ]"
+          echo "LIB_CACHE_PATHS=$LIB_CACHE_PATHS" >> $GITHUB_OUTPUT
+
+      - name: Remove old libraries that are cached.
+        run: |
+          echo "We really should remove old library caches here"
 
       - name: Install configuration
         uses: ChristopherHX/conditional@main
@@ -393,30 +424,57 @@ jobs:
             uses: ${{ matrix.target-build-data.install-uses.uses || '' }}
             with: ${{ (matrix.target-build-data.install-uses.with && toJSON(matrix.target-build-data.install-uses.with)) || '{}' }}
 
-#      - name: Cache Third Party Directory
-#        uses: GeniusVentures/cache-multi/restore@v3.2.2
-#        id: cache-tp-source-directory
-#        with:
-#          key: ${{ needs.setup-src-cache.outputs.THIRD_PARTY_CACHE_NAME_KEY }}
-#          path: |
-#            !.git/**
-#            ./**
-#
-#      - if: (steps.cache-tp-source-directory.outputs.cache-hit != 'true')
-#        run: |
-#          echo "Couldn't find cached thirdparty code, ${{ needs.setup-src-cache.outputs.THIRD_PARTY_CACHE_NAME_KEY }} fatal error!"
-#          exit 1
-#
-#      - name: Cache Submodule Source Files without .git
-#        id: cache-source-directory
-#        uses: GeniusVentures/cache-multi@v3.2.2
-#        with:
-#          key: ${{ needs.setup-src-cache.outputs.CACHE_MULTI_PARAMETER_NAME_KEYS }}
-#          path: ${{ needs.setup-src-cache.outputs.CACHE_MULTI_PARAMETER_PATHS }}
-#
-#
-#      - name: Get libraries to build libraries
-#        run: |
-#          # build array of library names
+      - name: Cache Third Party Directory
+        uses: GeniusVentures/cache-multi/restore@v3.2.3
+        id: cache-tp-source-directory
+        with:
+          key: ${{ needs.setup-src-cache.outputs.THIRD_PARTY_CACHE_NAME_KEY }}
+          path: |
+            !.git/**
+            ./**
 
+      - if: (steps.cache-tp-source-directory.outputs.cache-hit != 'true')
+        run: |
+          echo "Couldn't find cached thirdparty code, ${{ needs.setup-src-cache.outputs.THIRD_PARTY_CACHE_NAME_KEY }} fatal error!"
+          exit 1
 
+      - name: Cache Submodule Source Files without .git
+        id: cache-source-directory
+        uses: GeniusVentures/cache-multi/restoremulti@v3.2.3
+        with:
+          multi-keys: ${{ needs.setup-src-cache.outputs.CACHE_MULTI_PARAMETER_NAME_KEYS }}
+          paths: ${{ needs.setup-src-cache.outputs.CACHE_MULTI_PARAMETER_PATHS }}
+
+      - name: Init the CMake build files
+        run: |
+          TARGET_OS="${{ matrix.target-build-data.target-os }}"
+          BUILD_TYPE="${{ matrix.build-type }}"
+          ${{ matrix.target-build-data.cmake-init-script }}
+
+      - name: Load built library caches if any
+        id: cache-library-directory
+        uses: GeniusVentures/cache-multi/restoremulti@v3.2.3
+        with:
+          multi-keys: ${{ steps.create-lib-cache-keys.outputs.LIB_CACHE_NAME_KEYS }}
+          paths: ${{ steps.create-lib-cache-keys.outputs.LIB_CACHE_PATHS }}
+
+      - name: Build any updated libraries
+        run: |
+          TARGET_OS="${{ matrix.target-build-data.target-os }}"
+          BUILD_TYPE="${{ matrix.build-type }}"
+          IFS=$'\n' read -d '' -ra TARGET_NAMES <<< "${{ needs.create-targets-matrix.outputs.TARGET_NAMES }}"
+          IFS=$'\n' read -d '' -ra TARGET_SHAS <<< "${{ needs.create-targets-matrix.outputs.TARGET_SHAS }}"
+          IFS=$'\n' read -d '' -ra CACHE_HITS <<< "${{ steps.cache-library-directory.outputs.cache-hits }}"
+          for i in "${!TARGET_NAMES[@]}"; do
+            TARGET_NAME="${TARGET_NAMES[i]}"
+            TARGET_SHA="${TARGET_SHAS[i]}"
+            if [ "${CACHE_HITS[i]}" == "1" ]; then
+              echo "Skipping cached target: $TARGET_NAME, sha: $TARGET_SHA"
+            else
+              ${{ matrix.target-build-data.cmake-compile-script }}
+            fi
+          done
+
+      - name:  Save target OS SDK as an artifact
+        run: |
+          echo "We should save the artifact here"
